# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\edit_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editDialog(object):
    def setupUi(self, editDialog):
        editDialog.setObjectName("editDialog")
        editDialog.resize(400, 300)
        editDialog.setSizeGripEnabled(False)
        self.themeLabel = QtWidgets.QLabel(editDialog)
        self.themeLabel.setGeometry(QtCore.QRect(60, 53, 47, 20))
        self.themeLabel.setObjectName("themeLabel")
        self.questionLabel = QtWidgets.QLabel(editDialog)
        self.questionLabel.setGeometry(QtCore.QRect(60, 83, 51, 20))
        self.questionLabel.setObjectName("questionLabel")
        self.cardsLabel = QtWidgets.QLabel(editDialog)
        self.cardsLabel.setGeometry(QtCore.QRect(60, 143, 47, 20))
        self.cardsLabel.setObjectName("cardsLabel")
        self.answerLabel = QtWidgets.QLabel(editDialog)
        self.answerLabel.setGeometry(QtCore.QRect(60, 113, 47, 20))
        self.answerLabel.setObjectName("answerLabel")
        self.filePathLabel = QtWidgets.QLabel(editDialog)
        self.filePathLabel.setGeometry(QtCore.QRect(60, 173, 47, 20))
        self.filePathLabel.setObjectName("filePathLabel")
        self.themeLineEdit = QtWidgets.QLineEdit(editDialog)
        self.themeLineEdit.setGeometry(QtCore.QRect(140, 50, 191, 20))
        self.themeLineEdit.setObjectName("themeLineEdit")
        self.questionLineEdit = QtWidgets.QLineEdit(editDialog)
        self.questionLineEdit.setGeometry(QtCore.QRect(140, 80, 191, 20))
        self.questionLineEdit.setObjectName("questionLineEdit")
        self.answerLineEdit = QtWidgets.QLineEdit(editDialog)
        self.answerLineEdit.setGeometry(QtCore.QRect(140, 110, 191, 20))
        self.answerLineEdit.setObjectName("answerLineEdit")
        self.cardsLineEdit = QtWidgets.QLineEdit(editDialog)
        self.cardsLineEdit.setGeometry(QtCore.QRect(140, 140, 191, 20))
        self.cardsLineEdit.setObjectName("cardsLineEdit")
        self.filePathLineEdit = QtWidgets.QLineEdit(editDialog)
        self.filePathLineEdit.setGeometry(QtCore.QRect(140, 170, 191, 20))
        self.filePathLineEdit.setObjectName("filePathLineEdit")
        self.explanationLabel = QtWidgets.QLabel(editDialog)
        self.explanationLabel.setGeometry(QtCore.QRect(60, 203, 71, 20))
        self.explanationLabel.setObjectName("explanationLabel")
        self.explanationLineEdit = QtWidgets.QLineEdit(editDialog)
        self.explanationLineEdit.setGeometry(QtCore.QRect(140, 200, 191, 20))
        self.explanationLineEdit.setObjectName("explanationLineEdit")
        self.okBtn = QtWidgets.QPushButton(editDialog)
        self.okBtn.setGeometry(QtCore.QRect(120, 250, 75, 23))
        self.okBtn.setObjectName("okBtn")
        self.cancelBtn = QtWidgets.QPushButton(editDialog)
        self.cancelBtn.setGeometry(QtCore.QRect(210, 250, 75, 23))
        self.cancelBtn.setObjectName("cancelBtn")

        self.retranslateUi(editDialog)
        QtCore.QMetaObject.connectSlotsByName(editDialog)

    def retranslateUi(self, editDialog):
        _translate = QtCore.QCoreApplication.translate
        editDialog.setWindowTitle(_translate("editDialog", "Edit"))
        self.themeLabel.setText(_translate("editDialog", "Theme"))
        self.questionLabel.setText(_translate("editDialog", "Question"))
        self.cardsLabel.setText(_translate("editDialog", "Cards"))
        self.answerLabel.setText(_translate("editDialog", "Answer"))
        self.filePathLabel.setText(_translate("editDialog", "FilePath"))
        self.explanationLabel.setText(_translate("editDialog", "Explanation"))
        self.okBtn.setText(_translate("editDialog", "Ok"))
        self.cancelBtn.setText(_translate("editDialog", "Cancel"))
